export default Images = {
  champLogo: require("../assets/imgs/login-signup-Page-screen-logo.png"),
  bgGreen: require("../assets/imgs/bg.png"),
  splash: require("../assets/imgs/splash.png"),
  saina: require("../assets/imgs/saina.png"),
  back: require("../assets/imgs/arrow.png"),
  star: require("../assets/imgs/star.png"),
  star2: require("../assets/imgs/star2.png"),
  star3: require("../assets/imgs/pointed-star.png"),
  close: require("../assets/imgs/close.png"),
  dish: require("../assets/imgs/phirnidish.jpg"),
  reward: require("../assets/imgs/my-rewards.png"),
  dashboard: require("../assets/imgs/my-dashboard.png"),
  refer: require("../assets/imgs/Referafriend.png"),
  iphone: require("../assets/imgs/iphone.png"),
  user: require("../assets/imgs/user.jpeg"),
  avatar: require("../assets/imgs/avatar.png"),
  close: require("../assets/imgs/close.png"),
  gift: require("../assets/imgs/Group.png"),
  aadhar: require("../assets/profileimg/aadhar.png"),
  address: require("../assets/profileimg/address.png"),
  language: require("../assets/profileimg/language.png"),
  feedback: require("../assets/profileimg/send-feedback.png"),
  about: require("../assets/profileimg/About.png"),
  termcondition: require("../assets/profileimg/terms&condition.png"),
  privacypolicy: require("../assets/profileimg/Privacy&Policy.png"),
  edit: require("../assets/profileimg/edit.png"),
  contactus: require("../assets/profileimg/contactus.png"),
  congrat: require("../assets/imgs/congrat.png"),
  congrats2: require("../assets/imgs/congrats2.png"),
  logout: require("../assets/profileimg/Log-out.png"),
  dust: require("../assets/imgs/sparkling magical dust particles.png"),
}